### ISSUE TITLE
disable vibrate when timer is ongoing

### ISSUE THREAD

**Issue by alphajayGithub** [klimeryk/garmodoro#1]
Hi,
Why  enable vibrate when timer is ongoing?  
why not use use minutes:second directly, no vibrate, and vibrate & sound after timeout.

**Comment by julienbourdeau** [comment]
Go in your mobile app, find the settings of the Pomodoro app and set the `strengh of vibration` to zero.

This should probably be the default configuration, I doubt the majority of people wants they watch to vibrate every minute.

Once you will disable the vibration, you'll see it's a great app!

**Comment by alphajayGithub** [comment]
it works.

I'm so happy that having pomodoro app on garmin.
Thanks you :)


Brs,
Shen Yue (hugh)


2017-06-11 16:01 GMT+08:00 Julien Bourdeau <notifications@github.com>:

**Comment by ilbonte** [comment]
I agree that the vibration should be disabled as default.

**Comment by klimeryk** [comment]
Thank you for your feedback, everyone! (and sorry for late reply - for some reason, I did not subscribe to updates to my own repo...).
As hinted in the features list of this app:
> Mimics the ticking of a real physical Pomodoro by using short vibrations.

The "ticking" of the pomodoro when it's running was actually a crucial feature _for me_ when developing this app. That's because the ticking of a real Pomodoro/kitchen timer served as a great reminder for me to keep working and _not_ loose focus. I wanted to re-create that in this app in some form - the vibrations/"ticking" is a result of that.
I understand that it might not be to everyone's liking - that's why I mention clearly how to disable it in the documentation (plus in the settings page).

Before disabling it hastily, please give it a try over a few sessions. The thing is it _should_ be disruptive, but only when your mind starts to wonder off - that's when I notice the vibrations (and they remind me that I should go back to work).

Anyway, those are my reasons for having it enabled by default - this is a _Pomodoro_ app, not a timer one and I find the physical stimuli (be it ticking sound or "ticking" vibrations) crucial to the effectiveness of the technique. However, if you do not like it, you can easily disable it from the settings.

Closing this as `wontfix`.
