### ISSUE TITLE
Request: Access data from computer?

### ISSUE THREAD

**Issue by codemaestro** [klimeryk/garmodoro#16]
Hi Igor @klimeryk : I assume this is the same app I downloaded from Connect IQ. It's great for timing focused work/breaks. I'm not sure if it's possible to access the data from the device to use to create reports?

PS: While I would like the background run function, too, the app serves its purpose to make me *feel* like I'm working. 😄

**Comment by klimeryk** [comment]
Yup, it's the same app - thanks for reaching out here! Sorry for the late reply 🙇 

There's no historical data stored by app - it's all in the memory while the app is running and then cleaned when it's closed. I looked into trying to make this an "activity", that could show up in your Garmin dashboard, just like any other activity (running, cycling), possibly with graphs, but it did not seem to have been a good fit for that. That's because the data you'd be interested in is not the same as what Garmin expects. It'd be a boring graph showing a new pomodoro session every 30 minutes or so. Unless something has changed (it's been a year since I looked at this), there was no way (that I found) to show a more aggregate data like "how many pomodoros per day am I doing".

But I wonder if you should not look at this the other way around - you're not trying to measure how many pomodoros you're making, but how productive they are making you. So, maybe measure the output of your time spent doing the pomodoros. For example, I use a https://trello.com/ board to track my personal tasks and move them around the board as I make progress. It could be more interesting and useful to track the progress of things there (how many cards per day, etc.).

> PS: While I would like the background run function, too, the app serves its purpose to make me feel like I'm working. 😄

Yeah, now that I got a brand new Fenix 6, I'll look into the new way of handling background apps. Though, in my opinion, the current way is sort of a "feature" - it prevents you from checking other things on your watch and thus reduces distractions ;)

Definitely agree that the app makes you feel more productive! :D

----

I'll mark this as closed and wontfix - like I mentioned above, I feel there are other tools that could give you a better view of how productive you are. I guess it's akin to looking how many repetitions during physical exercise you can do vs actual muscle growth. You could be doing 1000 pushups, but if they are not actually straining your muscles and causing them to grow, they are useless :)
