### ISSUE TITLE
Back button doesn't work

### ISSUE THREAD

**Issue by MyroslavGryshyn** [klimeryk/garmodoro#2]
On my fenix 3 back button on main screen doesn't work, so I need to start/stop timer and then exit.

**Comment by steveeJ** [comment]
This looks to be the general case, since [back just returns true](https://github.com/klimeryk/garmodoro/blob/991e6e430af91e02cf8001ac9891d01b6638f7a4/source/GarmodoroDelegate.mc#L80).

**Comment by klimeryk** [comment]
Thanks for reporting! (and sorry for the super slow response - for some reason I was not subscribed to my own repo...)

If I remember correctly, I've done it that way because that was the only way to get back to the clock without exiting the app on Forerunner 735xt (one of the two watches I have for testing). Though, now that I've tested it again (I use Fenix 3 HR daily instead), it seems that there's no way to get back to the clock either way 🤔 On Fenix 3 HR, you just long press the Down button, but this doesn't seem to work on 735xt... Anyway, I've restored the default behaviour in https://github.com/klimeryk/garmodoro/commit/b1bf89d8b900085cb02aec5f1c72d95a810e19aa - hope you'll enjoy the app even more now!
