### ISSUE TITLE
Preloaded vs downloaded watch faces

### ISSUE THREAD

**Issue by Andriy8610** [klimeryk/garmodoro#24]
Hi, thanks for the app!
One request: when i press "Back" while the app is working, it sends me to one of the preloaded watch faces and it doesn't want to show downloaded watch face, which I'm actually using on a permanent basis.
Is it possible to fix this and ensure that the "Back" button sends to the actually applied watch face?

**Comment by klimeryk** [comment]
That's a limitation of the watch (depending on your model) - some watches support putting the running app in "background" by _long pressing_ the Back button. But some models (especially the older ones) simply don't offer that :(

The current behaviour is the correct/expected one, AFAIK - if you press Back in an active app, it should quit it (otherwise, you could end up with an unnecessary app working in the background, slowly draining battery).
