### ISSUE TITLE
Setting and notification during the countdown

### ISSUE THREAD

**Issue by YNDAoak** [klimeryk/garmodoro#4]
Hi,

I would like the meaning of "Duration of the vibration on every tick" ? its minimum no is 80 !! What does it mean ?

Also, during the countdown, the notification of whatsapp to my watch, Fenix 5 is disbable? 

Looking for some answer thx a lot

**Comment by klimeryk** [comment]
> I would like the meaning of "Duration of the vibration on every tick" ? its minimum no is 80 !! What does it mean ?

It's in miliseconds. The minimum is 80, because from my testing it seems that below that value the motor that causes the vibrations just doesn't have enough time to spin up and as an effect there are no vibrations. Hope this helps!

> Also, during the countdown, the notification of whatsapp to my watch, Fenix 5 is disbable?

Sorry, no idea what could be causing that, but I'd reach out to the WhatsApp developers/support. I don't do anything explicitly to disable those notifications.
