### ISSUE TITLE
Allow toggling vibration ticking from in-app settings

### ISSUE THREAD

**Issue by klimeryk** [klimeryk/garmodoro#5]
While I stand by my reasonings mentioned in https://github.com/klimeryk/garmodoro/issues/1#issuecomment-331624926, as stated there I understand that not everyone will agree with this feature. So as a compromise I'll try to introduce an easily toggleable setting inside the app itself - so that you don't need to search for it in the mobile app or Garmin Express. Plus, it's easier to discover the setting this way.

cc @alphajayGithub @julienbourdeau

**Comment by julienbourdeau** [comment]
Great! After your comment I wanted to try it again, and indeed it's painful to go and set it in the mobile app.

**Comment by jpgilman** [comment]
I strongly agree that ticking vibration should either be disabled by default or you should be able to control this from in-app settings.  And if the latter, it is important that it's obvious that you can do so.  Literally, the only reason I didn't uninstall this app after 10 seconds of use is that I happened to look at the reviews after trying it and saw a reference to being able to disable.  I understand that for those who struggle to focus, the ticking is helpful, but for at least some of those who don't, the ticking is a distraction.  None of the pomodoro apps on my Mac have a ticking function enabled by default.  Given the hot button nature of the ticking function, my other thought is that you consider moving the ability to control the ticking vibration to the top of the Features list, because Garmin only shows 2 by default.  I never bothered to read through the full list.  I simply saw Pomodoro app, saw 5 stars and downloaded.  All that said, great app!

**Comment by klimeryk** [comment]
Closing this as the vibrations have been disabled by default and you can toggle them from the settings in Garmin Express if needed.
